name: Feature Request
description: Suggest an idea or improvement for the project
labels: ["feature"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement 🙌
        Please describe the idea as clearly as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: It is currently difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see happen?
      placeholder: I would like the project to support...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Another approach could be...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Mockups, examples, links, or anything else that helps.
    validations:
      required: false
